plugins_enabled = ["-DDISABLE_PLUGINS_BY_DEFAULT=YES", "-DPLUGIN_DOMINANCE_PRUNING_ENABLED=YES", "-DPLUGIN_PLUGIN_LAZY_GREEDY_ENABLED=TRUE", "-DPLUGIN_BLIND_SEARCH_HEURISTIC_ENABLED=TRUE", "-DPLUGIN_PLUGIN_ASTAR_ENABLED=TRUE", "-DPLUGIN_RELAXATION_HEURISTIC_ENABLED=TRUE", "-DPLUGIN_MAX_HEURISTIC_ENABLED=TRUE", "-DPLUGIN_ADDITIVE_HEURISTIC_ENABLED=TRUE", "-DPLUGIN_FF_HEURISTIC_ENABLED=TRUE", "-DPLUGIN_MAS_HEURISTIC_ENABLED=TRUE","-DPLUGIN_SYMBOLIC_SEARCH_ENGINE_ENABLED=FALSE", "-DPLUGIN_PLUGIN_SAT_SEARCH_ENABLED=TRUE", "-DPLUGIN_SAT_SEARCH_ENABLED=TRUE"]

sat_solver = ["-DUSE_KISSAT=ON","-DUSE_CUSTOM_KISSAT=ON", "-DSAT_DIR=/home/alvaro/projects/joao/kissat-p/build", "-DSAT_LIB=kissat"]

release32 = ["-DCMAKE_BUILD_TYPE=Release"] + plugins_enabled + sat_solver
debug32 = ["-DCMAKE_BUILD_TYPE=Debug", "-DFORCE_DYNAMIC_BUILD=YES"] + plugins_enabled + sat_solver

release32nolp = ["-DCMAKE_BUILD_TYPE=Release", "-DUSE_LP=NO"]
debug32nolp = ["-DCMAKE_BUILD_TYPE=Debug", "-DUSE_LP=NO"]

release64 = release32 + ["-DALLOW_64_BIT=True", "-DCMAKE_CXX_FLAGS='-m64'"]
debug64 = debug32 + [ "-DALLOW_64_BIT=True", "-DCMAKE_CXX_FLAGS='-m64'"]

release64nolp = ["-DCMAKE_BUILD_TYPE=Release", "-DALLOW_64_BIT=True", "-DCMAKE_CXX_FLAGS='-m64'", "-DUSE_LP=NO"]
debug64nolp = ["-DCMAKE_BUILD_TYPE=Debug",   "-DALLOW_64_BIT=True", "-DCMAKE_CXX_FLAGS='-m64'", "-DUSE_LP=NO"]
minimal = ["-DCMAKE_BUILD_TYPE=Release", "-DDISABLE_PLUGINS_BY_DEFAULT=YES"]

release32dynamic = ["-DCMAKE_BUILD_TYPE=Release", "-DFORCE_DYNAMIC_BUILD=YES"]
debug32dynamic = ["-DCMAKE_BUILD_TYPE=Debug", "-DFORCE_DYNAMIC_BUILD=YES"]
release64dynamic = ["-DCMAKE_BUILD_TYPE=Release", "-DALLOW_64_BIT=True", "-DCMAKE_CXX_FLAGS='-m64'", "-DFORCE_DYNAMIC_BUILD=YES"]
debug64dynamic = ["-DCMAKE_BUILD_TYPE=Debug",   "-DALLOW_64_BIT=True", "-DCMAKE_CXX_FLAGS='-m64'", "-DFORCE_DYNAMIC_BUILD=YES"]

DEFAULT = "release64"
DEBUG = "debug64"



